name: peekr-b2b-automation
services:
- name: automation-engine
  source_dir: /
  github:
    repo: your-username/your-repo-name
    branch: main
    deploy_on_push: true
  run_command: python peekr_automation_master.py
  environment_slug: python
  instance_count: 1
  instance_size_slug: basic-xxs
  envs:
  - key: OPENAI_API_KEY
    scope: RUN_TIME
    type: SECRET
  - key: EMAIL_ACCOUNT
    scope: RUN_TIME
    type: SECRET
  - key: EMAIL_PASSWORD
    scope: RUN_TIME
    type: SECRET
  - key: SENDER_NAME
    scope: RUN_TIME
    value: "Your Name"
  - key: SMTP_SERVER
    scope: RUN_TIME
    value: "smtp.gmail.com"
  - key: SMTP_PORT
    scope: RUN_TIME
    value: "465"
  - key: IMAP_SERVER
    scope: RUN_TIME
    value: "imap.gmail.com"
  - key: IMAP_PORT
    scope: RUN_TIME
    value: "993"
  - key: GOOGLE_CREDENTIALS_FILE
    scope: RUN_TIME
    value: "credentials.json"
  - key: SPREADSHEET_ID
    scope: RUN_TIME
    type: SECRET
  - key: APIFY_API_KEY
    scope: RUN_TIME
    type: SECRET
  - key: TIMEZONE
    scope: RUN_TIME
    value: "Asia/Dubai"

- name: admin-dashboard
  source_dir: /
  github:
    repo: your-username/your-repo-name
    branch: main
    deploy_on_push: true
  run_command: streamlit run admin_dashboard.py --server.port $PORT --server.address 0.0.0.0
  environment_slug: python
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8080
  envs:
  - key: OPENAI_API_KEY
    scope: RUN_TIME
    type: SECRET
  - key: GOOGLE_CREDENTIALS_FILE
    scope: RUN_TIME
    value: "credentials.json"
  - key: SPREADSHEET_ID
    scope: RUN_TIME
    type: SECRET